theme: minima
title: PrivacyBlur
description: A cross-platform application to obfuscate sensitive areas in images
email: mobile@mathema.de
author: MATHEMA GmbH
header_pages:
  - screenshots.md
  - privacy.md